config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show] 
  
  resources :events do
    resources :activities, only: [:create,:update, :destroy, :show,:edit]
  end
  root 'welcome#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :event
  after_save :date?
  
  def self.date?(activity)
    activity.event.length == 'One Day' ? activity.event.startdate : activity.date
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many  :activities, dependent: :destroy
  after_save :length?
  scope :visible_to, -> (user) { user ? all : where(@events.user = @user) }
  
  geocoded_by :location
  after_validation :geocode
  
  def self.weather(event)
    event.geocode
    lat = event.latitude
    lng = event.longitude
    time = event.startdate.to_time.iso8601
    @weather = ForecastIO.forecast(lat, lng, time: time)
  end
  
  def self.length?(event)
    event.startdate == event.enddate ? event.length = 'One Day' : event.length = 'Mutiple Days'
  end
end

app/models/expedia.rb
require 'json'

class Expedia
  include HTTParty
  base_uri 'terminal2.expedia.com/x'
  format :json
  
  def initialize(latitude, longitude, check_in_date, check_out_date)
    expedia_api_key = Figaro.env.expedia_apikey 
    @options = { query: {city: 'Seattle', latitude: latitude, longitude: longitude, checkInDate: check_in_date, checkOutDate: check_out_date, room1: 2,resultsPerPage: 10, apikey: expedia_api_key} }
  end
  
  def hotel_search
    self.class.get("/mhotels/search", @options)
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :events
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def show
    @activity = Activity.find(params[:id])
    @event = @activity.event
    @event.geocode
    lat = @event.latitude
    lng = @event.longitude
    check_in_date = @event.startdate.strftime('%Y-%m-%d').to_s
    @event.enddate == check_in_date ? check_out_date = @event.startdate.tomorrow.strftime('%Y-%m-%d').to_s : check_out_date = @event.enddate.strftime('%Y-%m-%d').to_s
    #Show Expedia resources
    expedia = Expedia.new(lat, lng, check_in_date, check_out_date )
    @hotel_list = expedia.hotel_search["hotelList"]
  end
  def create
    @event = Event.find(params[:event_id])
    @activity = @event.activities.new(activity_params)
    p 'BEFORE DATE'
    p @activity.date
    @activity.date = Activity.date?(@activity)
    p 'AFTER DATE'
    p @activity.date
    
    if @activity.save
      flash[:notice] = "Activity was saved successfully."
      redirect_to @activity.event
    else
      flash.now[:alert] = "There was an error saving the activity. Please try again."
      redirect_to @activity.event
    end
  end
  def edit
    @event = Event.find(params[:event_id])
    @activity = @event.activities.find(params[:id])
  end
  def update
    @event = Event.find(params[:event_id])
    @activity = @event.activities.find(params[:id])
    @activity.completed = true
     if @activity.save
      redirect_to @activity.event
     else
       flash.now[:alert] = "There was an error saving the activity. Please try again."
      redirect_to @activity.event
     end
  end
  def destroy
    @activity = Activity.find(params[:id])

     if @activity.destroy
       flash[:notice] = "\"#{@activity.name}\" was deleted successfully."
       redirect_to @activity.event
     else
       flash.now[:alert] = "There was an error deleting the activity."
       redirect_to @activity.event
     end
  end
  
  private
 
  def activity_params
    params.require(:activity).permit(:name, :starttime, :completed, :date)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  ROLES = {0 => 'guest', 1 => 'user', 2 => 'helper', 3 => 'planner'}
  
  attr_reader :role
    
  def current_role
    if current_user && @event.user == current_user
      @role = ROLES[3]
    elsif current_user && @event.user != current_user
      @role = ROLES[2]
    elsif current_user
      @role = ROLES[1]
    else
      @role = ROLES[0]
    end
    p @role
  end
  helper_method :current_role
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
    @current_weather = Event.weather(@event).currently
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    @event.length = Event.length?(@event)
    
    if @event.save
      flash[:notice] = "Event was saved successfully."
      redirect_to @event
    else
      flash.now[:alert] = "There was an error saving the event. Please try again."
      render :new
    end
  end
  
  def edit
    @event = Event.find(params[:id])
  end
  
  def update
    @event = Event.find(params[:id])
    @event.assign_attributes(event_params)

     if @event.save
      flash[:notice] = "Event was updated successfully."
      redirect_to @event
     else
       flash.now[:alert] = "There was an error saving the event. Please try again."
       render :edit
     end
  end
  def destroy
     @event = Event.find(params[:id])

     if @event.destroy
       flash[:notice] = "\"#{@event.name}\" was deleted successfully."
       redirect_to @event
     else
       flash.now[:alert] = "There was an error deleting the event."
       render :show
     end
  end
  
  private
 
   def event_params
     params.require(:event).permit(:name, :startdate, :enddate, :location)
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
     css_class = 'form-group'
     css_class << ' has-error' if errors.any?

     content_tag :div, capture(&block), class: css_class
  end
  
  def event_info
    @event = Event.find(params[:id])
    @event.geocode
    @lat = @event.latitude
    @lng = @event.longitude
    @check_in_date = @event.startdate.strftime('%Y-%m-%d').to_s
    @event.enddate == @check_in_date ? @check_out_date = @event.startdate.tomorrow.strftime('%Y-%m-%d').to_s : @check_out_date =@event.enddate.strftime('%Y-%m-%d').to_s
  end
  
  #RESOURCE API
  #1 Hotel Resource - using Expedia API
  def hotels_as_json(hotel_list) 
    #Get Event Info first
    event_info
    
    #Using Event Info to retrieve Expedia resources
    expedia = Expedia.new(@lat, @lng, @check_in_date, @check_out_date )
    hotel_list = expedia.hotel_search["hotelList"]
    
    a = hotel_list.collect do |hotel|
      { :name => hotel['name'],
        :address => hotel['address'],
        :hotelGuestRating => hotel['hotelGuestRating'],
        :lowRate => hotel['lowRate']
      }
    end
  end
  
  #2 Weather Resource - using Forecast.io
end

app/helpers/events_helper.rb
module EventsHelper
  def user_is_authorized_for_events?
        current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/activities/_activity.html.erb
<td>
  <%= activity.date.strftime('%^b %e') %>
</td>
<td>
  <%= activity.starttime.strftime('%l:%M %P')  %>
</td>
<td>
  <%= activity.name %>
</td>  
<td>
    <% if current_role == 'planner' %>
      <div class='hearts btn btn-default'>
        <a data-transition="boring"><i class="glyphicon glyphicon-search"></i></a>
      </div>
      
      <%= link_to "", event_activity_path(activity.event, activity), method: :delete, class: 'btn btn-danger glyphicon glyphicon-remove' %>
      <% if activity.completed  %>
        <p class= 'glyphicon glyphicon-ok'></p>
      <% else %>
        <%= link_to '', event_activity_path(activity.event, activity), method: :put, class: 'btn btn-success glyphicon glyphicon-ok' %>
      <% end %>
    <% elsif current_role == 'helper' %> 
      <% if activity.completed  %>
        <p class= 'glyphicon glyphicon-ok'></p>
      <% else %>
        <%= link_to 'Completed', event_activity_path(activity.event, activity), method: :put, class: 'btn btn-success' %>
      <% end %>
    <% else %>
      Your current role is <%= current_role %>.
      Want to help <%= @event.user.email %> this event?
    <% end %>
</td>

app/views/activities/_form.html.erb
 <%= form_for [event, activity] do |f| %>
   
      <td>
        <%= f.label :date, class: 'sr-only' %>
        <%= f.text_field :date, class: 'form-control', type: 'date', :disabled => event.length == 'One Day' %>
      </td>
      <td>
        <%= f.label :starttime, class: 'sr-only'  %>
        <%= f.text_field :starttime, class: 'form-control', placeholder: "Time" %>
      </td>
      <td>
        <%= f.label :name, class: 'sr-only' %>
        <%= f.text_field :name, class: 'form-control search-input', placeholder: "Enter a new activity" %>
      </td>  
      <td>
        <%= f.submit "Submit", class: 'btn btn-default pull-right' %>
      </td>
   
 <% end %>

app/views/activities/edit.html.erb
<%= render 'activities/form', event: @event, activity: @activity %>

app/views/activities/new.html.erb
<h1>Activities#new</h1>
<p>Find me in app/views/activities/new.html.erb</p>

app/views/activities/show.html.erb
<div class="row">
  <div class="col-md-6">
    <small><%= @activity.event.name %></small>
    <h1><%= @activity.name %></h1>
  </div>
</div>
<div class="row">
  <div class="col-md-8">
    <%= hotels_as_json(@hotel_list) %>
  </div>
</div>

app/views/activities/update.html.erb
<h1>Activities#update</h1>
<p>Find me in app/views/activities/update.html.erb</p>

app/views/events/_form.html.erb
<%= form_for [event] do |f| %>
   <% if event.errors.any? %>
     <div class="alert alert-danger">
       <h4><%= pluralize(event.errors.count, "error") %>.</h4>
       <ul>
         <% event.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>
   <%= form_group_tag(event.errors[:name]) do %>
     <%= f.label :name %>
     <%= f.text_field :name, class: 'form-control', placeholder: "Memorable Event Name" %>
     
     <%= f.label :startdate %>
     <%= f.text_field :startdate, class: 'form-control', type: "date" %>
     
     <%= f.label :enddate %>
     <%= f.text_field :enddate, class: 'form-control', type: "date" %>
     
     <%= f.label :location %>
     <%= f.text_field :location, class: 'form-control', placeholder: "Location" %>
  <% end %>
   <div class="form-group">
     <%= f.submit "Save",  class: 'btn btn-success' %>
   </div>
<% end %>

app/views/events/edit.html.erb
<div class="row">
  <div class="col-md-8">
    <h3>Edit</h3>
    <%= render partial: 'events/form', locals: {event: @event} %>
  </div>
</div>

app/views/events/index.html.erb
<h1>All Events</h1>
<div class="row">
  <div class="col-md-8">
    <% @events.each do |event| %>
    </br>
      <%= link_to event.name, event_path(event) %>
      - <%= event.location %>
      </br>
      <% if event.startdate == event.enddate %>
        <%= event.startdate.strftime('%b %e, %Y') %>
      <% else %>
        <%= event.startdate.strftime('%b %e, %Y') %> - <%= event.enddate.strftime('%b %e, %Y') %>
      <% end %>
    <% end %>
  </div>
  <% if current_user %>
    <div class="col-md-4">
      <%= link_to "New Event", new_event_path, class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>
<div class="row">
  <div class="col-md-8">
    <%= render partial: 'form', locals: { user: @user, event: @event } %>
  </div>
</div>

app/views/events/show.html.erb
<!--Cover-->
<div class="jumbotron" id="cover-picture">
  <div class="container text-center" id="cover-text">
    <h1><%= @event.name %></h1>
    <p><% if @event.length == 'One Day' %>
      <%= @event.startdate.strftime('%b %e, %Y') %>
      <% else %>
      <%= @event.startdate.strftime('%b %e, %Y') %> - <%= @event.enddate.strftime('%b %e, %Y') %>
      <% end %>
    </p>
    <p><%= @event.location %></p>
  </div>
</div>

<div id="site-canvas">
  <div id="site-menu">
    <strong>Resource List</strong>
    <%= hotels_as_json(@hotel_list) %>
  </div>
  <div id="activity" class="container">
    <table id="activity-list-table" class="table table-striped table-bordered">
      <thead>
        <th class="col-sm-2">Date</th>
        <th class="col-sm-2">Time</th>
        <th class="col-sm-4">Activity Name</th>
        <th class="col-sm-3">Actions</th>
      </thead>
      <tbody>
        <% @event.activities.each do |activity| %>
          <tr id="activity-detail-rows">
            <%= render 'activities/activity', activity: activity%>
          </tr>
        <% end %>
      
        
          <% if current_role == 'planner' || current_role == 'helper' %>
            <tr><%= render 'activities/form', event: @event, activity: Activity.new %></tr>
          <% end %>  
        
      </tbody>
    </table>
    
  </div>
      <br>

      <div class="row text-center">
        <% if current_role == 'planner' %>
            <%= link_to "Delete Event", @event, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this event?' } %>
            <%= link_to "Edit Event", edit_event_path, class: 'btn btn-default' %>
          <% end %>
      </div>
    
    </div>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Unwind</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Unwind</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Unwind", events_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to current_user.email, user_path(current_user.id), :class => 'navbar-link' %></li> 
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
          <% else %> 
            <li><%= link_to "Sign In", user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class = "flash">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash.now[:alert] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash.now[:alert] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
  </div>
    <div id="site-wrapper">
      <%= yield %>
      
    </div>
  

</body>
</html>

app/views/users/show.html.erb
<h1>Profile</h1>
<div class="row">
  <div class="col-md-8">
    <%= @user.email %>
  </div>
</div>
<div class="row">
  <div class="col-md-8">
    <%= link_to "Edit Your Account",  edit_user_registration_path(current_user.id), class: 'btn btn-success' %>
  </div>
</div>
<h1>Events created by you</h1>
<% @user.events.each do |event| %>
  <div class="row">
    <div class="col-md-8">
      <%= link_to event.name, event_path(event) %>
      </br>
      <small>Start: <%= event.startdate %></small>
      </br>
      <small>End: <%= event.enddate %></small>
    </div>
  </div>  
<% end %> 

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>